version: "3"

services:
    aerologic:
        container_name: aerologic
        build:
            context: .
            dockerfile: Dockerfile
        image: aerologic-image
        tty: true
        volumes:
            - .:/root/workspace/dev
        ### Comment/Delete the following lines to disable display forwarding ###
            - /tmp/.X11-unix:/tmp/.X11-unix
        environment:
            - DISPLAY=${DISPLAY}
        network_mode: "host"
        ipc: "host"
