version: "3"

services:
    aerologic:
        container_name: aerologic
        build:
            context: .
            dockerfile: Dockerfile
        image: aerologic-image
        volumes:
            - .:/root/workspace/dev
        ### Uncomment the following lines for display forwarding ###
            #- /tmp/.X11-unix:/tmp/.X11-unix
        #environment:
            #- DISPLAY=${DISPLAY}
        #network_mode: "host"
        #ipc: "host"
        tty: true
